apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pg-kinetic.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pg-kinetic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  pg-kinetic.toml: |
{{ .Values.config | indent 4 }}
